# Generated by Django 3.0 on 2019-12-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='countries',
        ),
    ]
