# Generated by Django 3.0 on 2019-12-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0002_auto_20191212_1349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
